version: '2'
services:
  gocdserver:
    build: server
    hostname: gocd-server
    ports:
      - '8153:8153'
    volumes:
      - ${PWD}/server/_data:/godata

  gocdagentnodejs:
    image: derrickwilliams/gocd-node-js-7.8-user-fix:v17.3.0
    links:
      - gocdserver
    env_file: .env
    volumes:
      - ${PWD}/agent/_data:/godata
